name: build
on:
  schedule:
    # Execute at 2am EST every day
    - cron: '0 21 * * *'
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build local image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: hello-world:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'hello-world:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'