name: build
on:
  schedule:
    # Execute at 2am EST every day
    - cron: '0 21 * * *'
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: localhost:5000/hello-world:${{ github.sha }}

      # Scan image for vulnerabilities
      - uses: Azure/container-scan@v0
        with:
          image-name: localhost:5000/hello-world:${{ github.sha }}
          severity-threshold: CRITICAL
